dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
    - ./node_modules

before_install:
  #  - npm install -g @lhci/cli
  #  - npm install -g codacy-coverage

install:
  - npm install

script:
  - ng lint
  - ng build --prod --base-href https://kamilzasada.github.io/angular-tour-of-heroes/
  #  - npm run test:coverage | codacy-coverage
  #  - lhci autorun --rc-overrides.upload.target=temporary-public-storage

#addons:
#  chrome: stable

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angular-tour-of-heroes
  on:
    branch: master
