dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

sources:
  - google-chrome
packages:
  - google-chrome-stable

cache:
  directories:
    - ./node_modules

before_install:
  #  - npm install -g @lhci/cli

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run ci:lint
  - npm run ci:build -- --base-href https://kamilzasada.github.io/angular-tour-of-heroes/
  - npm run ci:coverage
  #  - lhci autorun --rc-overrides.upload.target=temporary-public-storage

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

#addons:
#  chrome: stable

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/angular-tour-of-heroes
  on:
    branch: master
