dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - ng lint
  - ng build --prod --base-href https://kamilzasada.github.io/angular-tour-of-heroes/
